export default {
  NEW_RESOURCE: 'NEW_RESOURCE',
  CANCEL_NEW_RESOURCE: 'CANCEL_NEW_RESOURCE',
  CREATE_RESOURCE: 'CREATE_RESOURCE',
  CREATE_RESOURCE_SUCCEEDED: 'CREATE_RESOURCE_SUCCEEDED',

  NEW_ACTIVITY: 'NEW_ACTIVITY',
  CANCEL_NEW_ACTIVITY: 'CANCEL_NEW_ACTIVITY',
  CREATE_ACTIVITY: 'CREATE_ACTIVITY',
  CREATE_ACTIVITY_SUCCEEDED: 'CREATE_ACTIVITY_SUCCEEDED',

  NEW_STREAM: 'NEW_STREAM',
  CANCEL_NEW_STREAM: 'CANCEL_NEW_STREAM',
  CREATE_STREAM: 'CREATE_STREAM',
  CREATE_STREAM_SUCCEEDED: 'CREATE_STREAM_SUCCEEDED',
}
