export default {
  REGROUP_STREAMS: 'REGROUP_STREAMS',

  CHANGE_ACTIVE_STREAM: 'CHANGE_ACTIVE_STREAM',

  UPDATE_STREAM_DAY_SELECTION: 'UPDATE_STREAM_DAY_SELECTION',

  UPDATING_STREAM_DAYS: 'UPDATING_STREAM_DAYS',
  UPDATE_STREAM_DAYS_SUCCEEDED: 'UPDATE_STREAM_DAYS_SUCCEEDED',
  UPDATE_STREAM_DAYS_FAILED: 'UPDATE_STREAM_DAYS_FAILED',

  NEW_RESOURCE: 'NEW_RESOURCE',
  CANCEL_NEW_RESOURCE: 'CANCEL_NEW_RESOURCE',
  CREATING_RESOURCE: 'CREATING_RESOURCE',
  CREATE_RESOURCE_SUCCEEDED: 'CREATE_RESOURCE_SUCCEEDED',
  CREATE_RESOURCE_FAILED: 'CREATE_RESOURCE_FAILED',

  EDIT_RESOURCE: 'EDIT_RESOURCE',
  CANCEL_EDIT_RESOURCE: 'CANCEL_EDIT_RESOURCE',
  UPDATING_RESOURCE: 'UPDATING_RESOURCE',
  UPDATE_RESOURCE_SUCCEEDED: 'UPDATE_RESOURCE_SUCCEEDED',
  UPDATE_RESOURCE_FAILED: 'UPDATE_RESOURCE_FAILED',

  NEW_ACTIVITY: 'NEW_ACTIVITY',
  CANCEL_NEW_ACTIVITY: 'CANCEL_NEW_ACTIVITY',
  CREATING_ACTIVITY: 'CREATING_ACTIVITY',
  CREATE_ACTIVITY_SUCCEEDED: 'CREATE_ACTIVITY_SUCCEEDED',
  CREATE_ACTIVITY_FAILED: 'CREATE_ACTIVITY_FAILED',

  EDIT_ACTIVITY: 'EDIT_ACTIVITY',
  CANCEL_EDIT_ACTIVITY: 'CANCEL_EDIT_ACTIVITY',
  UPDATING_ACTIVITY: 'UPDATING_ACTIVITY',
  UPDATE_ACTIVITY_SUCCEEDED: 'UPDATE_ACTIVITY_SUCCEEDED',
  UPDATE_ACTIVITY_FAILED: 'UPDATE_ACTIVITY_FAILED',
}
