const BORDER_THICKNESS = 1
const STREAM_MARGIN = 2
const STREAM_CONTAINER_HEIGHT = 56
const STREAM_HEIGHT = STREAM_CONTAINER_HEIGHT - 2 * STREAM_MARGIN

export default {
  BORDER_THICKNESS: BORDER_THICKNESS,
  DAY_WIDTH: 28,
  STREAM_HEIGHT: STREAM_HEIGHT,
  STREAM_MARGIN: STREAM_MARGIN,
  STREAM_CONTAINER_HEIGHT: STREAM_CONTAINER_HEIGHT,
  STREAM_LABEL_WIDTH: 260,
  HOUR_HEIGHT: 3,
}
