import { spacing } from '../themes/customLightTheme'

const BORDER_THICKNESS = 1
const STREAM_SPACING = 5
const STREAM_CONTAINER_HEIGHT = 56
const STREAM_HEIGHT = STREAM_CONTAINER_HEIGHT - 2 * STREAM_SPACING

export default Object.assign({
  BORDER_THICKNESS: BORDER_THICKNESS,
  DAY_WIDTH: 30,
  STREAM_HEIGHT: STREAM_HEIGHT,
  STREAM_SPACING: STREAM_SPACING,
  STREAM_CONTAINER_HEIGHT: STREAM_CONTAINER_HEIGHT,
  STREAM_LABEL_WIDTH: 260,
  STREAM_LABEL_INDENT: 48,
  HOUR_HEIGHT: 4,
  SCHEDULE_BOTTOM_PADDING: 350,
}, spacing)
